fix: extend validation schemas to allow dates across all timezones and all possible tag values
sse-secure-systems/connaisseur pull request #15
Opened 2020-10-08 11:18 UTC by annekebr

The current schemas for trust data validation neither allow timezones with negative offsets nor tags containing dashes. This fixes both and adds additional tests.

Fix #10

2020-10-08 12:20 UTC, peterthomassen commented on connaisseur/tests/test_trust_data.py
> +        (trust_data("tests/data/sample_releases.json"), "targets/releases")
No need for this change. Also, you probably didn't run the Black code formatter; I think it puts in the comma?

2020-10-08 12:24 UTC, peterthomassen requested changes
Looks pretty good!

- Let's use the Black code formatter for consistency
- Make sure your commit title is short enough so that GitHub doesn't shorten it (something like 70 characters?)

After that, I'll approve.

In the future, it would be great to keep commits smaller, i.e. have one for the timezone issue, and one for the tag issue. No need to untangle this now.

2020-10-08 12:24 UTC, peterthomassen commented on connaisseur/tests/test_trust_data.py
> +        (trust_data("tests/data/sample4_targets.json"), "targets")
comma in the end is better

2020-10-08 12:24 UTC, peterthomassen commented on connaisseur/tests/test_trust_data.py
> +        (trust_data("tests/data/sample5_targets.json"), "targets")
comma

2020-10-08 13:33 UTC, peterthomassen submitted a review, later dismissed

2020-10-08 14:02 UTC, xopham reviewed
Really cool! Just one thing I am uncertain about: I think this may not actually check the `format:` specification, as you have to set `format_checker` parameter in `jsonschema.validate`. See: https://python-jsonschema.readthedocs.io/en/stable/validate/

_format_checker – an instance of FormatChecker whose FormatChecker.conforms method will be called to check and see if instances conform to each format property present in the schema. If unprovided, no validation will be done for format. Certain formats require additional packages to be installed (ipv5, uri, color, date-time). The required packages can be found at the bottom of this page._

2020-10-09 09:24 UTC, phbelitz approved these changes

2020-10-09 09:26 UTC, merged