docs: pipeline rework ADR
sse-secure-systems/connaisseur pull request #1787
Opened 2024-10-18 10:22 UTC by phbelitz

For now, only an ADR for a potetial pipeline rework.

## Checklist

- [ ] PR is rebased to/aimed at branch `develop`
- [ ] PR follows [Contributing Guide](https://github.com/sse-secure-systems/connaisseur/blob/master/docs/CONTRIBUTING.md)
- [ ] Added tests (if necessary)
- [ ] Extended README/Documentation (if necessary)
- [ ] Adjusted versions of image and Helm chart in `Chart.yaml` (if necessary)

2024-10-18 12:00 UTC, Starkteetje requested changes

2024-10-18 12:26 UTC, phbelitz commented on docs/adr/ADR-10_pipeline.md
> +            - ~~print summary~~  *// no one is looking at this*
If you have seen value in this at some point we can leave it. I didn't, so I would have kicked it out, but I also have no hard feeling towards keeping it.

2024-10-18 12:37 UTC, phbelitz commented on docs/adr/ADR-10_pipeline.md
> +        - (ossf [scoring for open source projects])  *// only on push, not pr*
well then let's drop it entirely.

2024-10-18 12:40 UTC, phbelitz commented on docs/adr/ADR-10_pipeline.md
> +1. Let the workflows be in the `workflow` directory and put the reusable parts into it's own (e.g. `reusable` or `components` :shrug:).
That sucks. I crossed that point.

2024-10-18 12:44 UTC, phbelitz commented on docs/adr/ADR-10_pipeline.md
> +        - (codeql [GitHub's "industry-leading" semantic code analysis engine])  *// only on push, not pr as this is by far the slowest*
Again. If you have a strong feeling this provides value during development, we can keep it. I would have just thrown out everything that didn't seem super necessary to me (in this case it's not even throwing out, but do it less frequently, without loosing its value entirely).

2024-10-25 07:36 UTC, Starkteetje commented
We'll likely work on the pipeline and streamline it, but not in the grand scale that we'll use an ADR for

2024-10-25 07:36 UTC, closed without merging