fix: satisfy new pylint rule
sse-secure-systems/connaisseur pull request #314
Opened 2021-09-17 14:10 UTC by annekebr

To enable the `pylint` update suggested by dependabot we need to satisy a newly introduce linting rule.

2021-09-24 13:31 UTC, phbelitz requested changes
:japanese_ogre:

2021-09-24 13:31 UTC, phbelitz commented on connaisseur/validators/notaryv1/notary.py
> +        auth_type_re = re.compile(f"""({"|".join(auth_types)}) realm""")
```suggestion
        auth_type_re = re.compile(f'({"|".join(auth_types)}) realm')
```

2021-09-24 15:24 UTC, phbelitz approved these changes

2021-10-01 09:21 UTC, xopham submitted a review, later dismissed
lgtm!

2021-10-01 09:35 UTC, xopham approved these changes
lgtm

2021-10-01 09:36 UTC, merged