Refactor: cosign key types
sse-secure-systems/connaisseur pull request #415
Opened 2021-11-12 16:55 UTC by xopham

Fixes no issue

## Description

- several different types of keys (ecdsa, rsa) and references (email, kms) are being added to cosign and integrated for connaisseur
- the handling and identification of key type is being refactored to improve extension

## Checklist

- [x] PR is rebased to/aimed at branch `develop`
- [x] PR follows [Contributing Guide](../docs/CONTRIBUTING.md)
- [x] Added tests (if necessary)
- [x] Extended README/Documentation (if necessary)
- [x] Adjusted versions of image and Helm chart in `values.yaml` and `Chart.yaml` (if necessary)

2021-11-12 22:04 UTC, peterthomassen requested changes
Nice! Nits only.

For the record, you *may* be able to do achieve a similar thing using new syntax from https://www.python.org/dev/peps/pep-0636/ (starting Python 3.10). However, it would be not what the new syntax is meant for, which reduces clarity, so I'd advise against it.

2021-11-12 22:23 UTC, xopham commented on connaisseur/validators/cosign/cosign_validator.py
> +        msg = "Public key (reference) '{key}' does not match expected patterns."
actually this is misleading as key is defined below as being `pubkey`, but I agree this is a circular reference and will fix that

2021-11-12 23:04 UTC, peterthomassen commented on connaisseur/validators/cosign/cosign_validator.py
> +        msg = "Public key (reference) '{key}' does not match expected patterns."
My bad, sorry! I thought `msg` was a format string, but it's being interpreted by the exception constructor. Never mind!

2021-11-13 11:57 UTC, peterthomassen submitted a review, later dismissed
lgtm!

2021-11-14 12:09 UTC, peterthomassen approved these changes

2021-11-14 19:09 UTC, merged