Only deploy ConfigMaps and Secrets if needed
sse-secure-systems/connaisseur pull request #958
Opened 2023-03-20 12:57 UTC by Starkteetje

Only deploy alerting ConfigMap and Secret if defined

## Description
Previously, we deployed some resources even if they weren't used in the deployment. This reduces the number of instances where that happens

## Checklist

- [x] PR is rebased to/aimed at branch `develop`
- [x] PR follows [Contributing Guide](https://github.com/sse-secure-systems/connaisseur/blob/master/docs/CONTRIBUTING.md)
- [x] Added tests (if necessary)
- [x] Extended README/Documentation (if necessary)
- [x] Adjusted versions of image and Helm chart in `values.yaml` and `Chart.yaml` (if necessary)

2023-03-20 15:49 UTC, xopham commented on tests/integration/integration-test.sh
> +set -euxo pipefail
not a big fan of wildly making fixes at completely different points. Feel free to make a comment on #944

2023-03-21 07:43 UTC, xopham requested changes
In order to not have unrelated changes in other files and avoid merge conflicts, I'd prefer to keep PRs focused on main goal

2023-03-21 07:43 UTC, xopham commented on tests/integration/integration-test.sh
> +cp helm/values.yaml values.yaml.backup
Again very unrelated change. Fixed in other PR already.

2023-03-21 07:43 UTC, xopham commented on tests/integration/integration-test.sh
> +debug_values() { #PATH
Same

2023-03-21 07:43 UTC, xopham commented on tests/integration/integration-test.sh
> +	debug_values "release_patched.yaml"
Same

2023-03-21 07:43 UTC, xopham commented on tests/integration/integration-test.sh
> +	debug_values "helm/values.yaml"
Same

2023-03-23 15:54 UTC, phbelitz submitted a review, later dismissed

2023-03-23 15:54 UTC, phbelitz commented on helm/templates/_helpers.tpl
> +{{- range .Values.validators     -}}
```suggestion
{{- range .Values.validators -}}
```
SPACE 👾

2023-03-23 17:21 UTC, merged